<?php

namespace Tests\Unit;

use App\Models\Tasting;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\TestCase;

class TastingTest extends TestCase
{
    protected $tasting;
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Tasting::factory()->count(5)->create();
    }

    /** @Test */
    public function test_get_all_tastings()
    {
        $response = $this->json('GET', '/api/tastings');

        $response->assertStatus(200);
    }
}
